steps:
  # 1. Install Dependencies
- name: 'node:20.19.0'
  id: install
  entrypoint: 'npm'
  args: ['install']

  # 3. Build the Application
- name: 'node:20.19.0'
  id: build
  entrypoint: 'npm'
  args: ['run', 'build']

  # 5. Run Tests (Optional, but HIGHLY recommended)
# - name: 'node:20.19.0'
#   id: test
#   entrypoint: 'npm'
#   args: ['run', 'test']

options:
  substitutionOption: ALLOW_LOOSE # Required for using custom substitution variables
  dynamicSubstitutions: true      # Use dynamic build parameters
  logging: CLOUD_LOGGING_ONLY